ktor:
  application:
    modules:
      - ru.otus.otuskotlin.adoptabletails.app.ktor.ApplicationKt.module
  deployment:
    port: 7102
  watch:
    - classes
    - resources
adoptable-tails:
  repository:
    test: "cassandra"
    prod: "cassandra"
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: test_keyspace
      username: cassandra
      password: cassandra


jwt:
  issuer: "http://localhost:8081/auth/realms/adoptable-tails-exchange"
  audience: "ad-user"
  realm: "adoptable-tails-realm"
  clientId: "adoptable-tails-ad"
  certUrl: "http://localhost:8081/auth/realms/adoptable-tails-exchange/protocol/openid-connect/certs" # TODO()