ktor:
  application:
    modules:
      - ru.otus.otuskotlin.adoptabletails.app.ktor.ApplicationKt.module
  deployment:
    port: 8080
  watch:
    - classes
    - resources
adoptable-tails:
  repository:
    test: "cassandra"
    prod: "cassandra"
    cassandra:
      host: cassandra
      port: 9042
      keyspace: test_keyspace
      username: cassandra
      password: cassandra

jwt:
  issuer: "http://localhost:8081/auth/realms/adoptable-tails"
  audience: "ad-users"
  realm: "adoptable-tails"
  clientId: "adoptable-tails-client"
  certUrl: "http://keycloak:8080/auth/realms/adoptable-tails/protocol/openid-connect/certs"