ktor:
  application:
    modules:
      - ru.otus.otuskotlin.adoptabletails.app.ktor.ApplicationKt.module
  deployment:
    port: 7102
  watch:
    - classes
    - resources
crypto:
  repository:
    test: "cassandra"
    prod: "cassandra"
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: test_keyspace
      username: cassandra
      password: cassandra