ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "ru.otus.otuskotlin.adoptabletails.app.ktor.ApplicationKt.module"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"