openapi: 3.0.4
info:
  title: Adoptable tails log models
  description: Log models for logging services of
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: { }

components:
  schemas:
    CommonLogModel:
      title: Common log model
      description: Common log model for all microservices
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        prgrp:
          $ref: '#/components/schemas/PetAdLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    PetAdLogModel:
      title: Log model for microservice Down work
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestPetAd:
          $ref: '#/components/schemas/PetAdLog'
        requestFilter:
          $ref: '#/components/schemas/PetAdFilterLog'
        responsePetAd:
          $ref: '#/components/schemas/PetAdLog'
        responsePetAds:
          type: array
          items:
            $ref: '#/components/schemas/PetAdLog'

    ErrorLogModel:
      title: Log model for error
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    PetAdLog:
      title: Log model for pet ad
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        properties:
          type: array
          uniqueItems: true
          items:
            $ref: './specs-v1.yaml#/components/schemas/PetAdId'
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    PetAdFilterLog:
      title: Log model for filter
      properties:
        petType:
          type: string
        temperament:
          type: string
